<a href="https://colab.research.google.com/github/JakeOh/202105_itw_bd26/blob/main/lab_da/da01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


* NumPy: 다차원 배열을 다루는 패키지. 머신러닝 패키지(scikit-learn)에서 중요하게 사용됨.
* pandas: 데이터프레임(DataFrame)과 시리즈(Series)를 다루는 패키지. 데이터 분석에서 기본으로 사용됨.
* matplotlib: 데이터 시각화.
* Google Colab에는 필요한 패키지들이 이미 설치되어 있음.
    * import 문을 사용해서 모듈과 모듈의 함수, 클래스들을 사용할 수 있음.


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

In [2]:
# Google Colab에 설치된 패키지 버전 확인 - 가장 최신 버전은 아님!
print('NumPy version:', np.__version__)
print('pandas version:', pd.__version__)
print('matplotlib version:', matplotlib.__version__)

NumPy version: 1.19.5
pandas version: 1.1.5
matplotlib version: 3.2.2


# Python list

* 여러개의 값들을 저장할 수 있는 데이터 타입
* 인덱스를 기반으로 값들을 저장하는 데이터 타입
    * indexing: 인덱스로 원하는 위치의 값을 참조
    * slicing: start <= index < end 범위의 값들의 부분집합(list)을 만듦
* `list + list`: extend 메서드와 비슷. 두 리스트를 이어붙여서 하나의 리스트로 만듦.
* `list * int`, `int * list`: list의 원소들을 정수 개수만큼 반복해서 추가.


In [10]:
num_list1 = [1, 2, 3]
num_list2 = [10, 20, 30]

In [11]:
num_list1

[1, 2, 3]

In [12]:
print(num_list1[0])  # indexing
print(num_list1[:1])  # slicing

1
[1]


In [13]:
num_list1 + num_list2

[1, 2, 3, 10, 20, 30]

In [14]:
num_list1.extend(num_list2)
num_list1

[1, 2, 3, 10, 20, 30]

In [15]:
num_list2 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

# NumPy(Numerical Python)

* 배열(array)을 쉽고 빠르게 연산(+, -, *, /, ...)하기 위한 라이브러리
* NumPy 패키지의 대부분의 기능(함수, 메서드)들은 반복문의 기능을 가지고 있음.
    * 같은 인덱스의 원소들끼리(element-wise) 연산을 수행.
* np.ndarray 클래스: NumPy 패키지의 기본 데이터 타입. n-dimensional array(n차원 배열).


In [17]:
num_list1 = [1, 2, 3]
num_list2 = [10, 20, 30]
# 같은 인덱스의 원소들끼리 더하기한 결과
add = [x + y for x, y in zip(num_list1, num_list2)]
add

[11, 22, 33]

In [19]:
num_arr1 = np.array([1, 2, 3])
print(type(num_arr1))
print(num_arr1)

<class 'numpy.ndarray'>
[1 2 3]


In [20]:
num_arr2 = np.array([10, 20, 30])
print(num_arr2)

[10 20 30]


In [21]:
num_arr1 + num_arr2

array([11, 22, 33])

In [22]:
num_arr1 * num_arr2

array([10, 40, 90])

In [26]:
num_list1 + num_arr1  # np.array(num_list1) + num_arr1

array([2, 4, 6])