<a href="https://colab.research.google.com/github/JakeOh/202105_itw_bd26/blob/main/lab_da/da01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


* NumPy: 다차원 배열을 다루는 패키지. 머신러닝 패키지(scikit-learn)에서 중요하게 사용됨.
* pandas: 데이터프레임(DataFrame)과 시리즈(Series)를 다루는 패키지. 데이터 분석에서 기본으로 사용됨.
* matplotlib: 데이터 시각화.
* Google Colab에는 필요한 패키지들이 이미 설치되어 있음.
    * import 문을 사용해서 모듈과 모듈의 함수, 클래스들을 사용할 수 있음.


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

In [2]:
# Google Colab에 설치된 패키지 버전 확인 - 가장 최신 버전은 아님!
print('NumPy version:', np.__version__)
print('pandas version:', pd.__version__)
print('matplotlib version:', matplotlib.__version__)

NumPy version: 1.19.5
pandas version: 1.1.5
matplotlib version: 3.2.2


# Python list

* 여러개의 값들을 저장할 수 있는 데이터 타입
* 인덱스를 기반으로 값들을 저장하는 데이터 타입
    * indexing: 인덱스로 원하는 위치의 값을 참조
    * slicing: start <= index < end 범위의 값들의 부분집합(list)을 만듦
* `list + list`: extend 메서드와 비슷. 두 리스트를 이어붙여서 하나의 리스트로 만듦.
* `list * int`, `int * list`: list의 원소들을 정수 개수만큼 반복해서 추가.


In [10]:
num_list1 = [1, 2, 3]
num_list2 = [10, 20, 30]

In [11]:
num_list1

[1, 2, 3]

In [12]:
print(num_list1[0])  # indexing
print(num_list1[:1])  # slicing

1
[1]


In [13]:
num_list1 + num_list2

[1, 2, 3, 10, 20, 30]

In [14]:
num_list1.extend(num_list2)
num_list1

[1, 2, 3, 10, 20, 30]

In [15]:
num_list2 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

# NumPy(Numerical Python)

* 배열(array)을 쉽고 빠르게 연산(+, -, *, /, ...)하기 위한 라이브러리
* NumPy 패키지의 대부분의 기능(함수, 메서드)들은 반복문의 기능을 가지고 있음.
    * 같은 인덱스의 원소들끼리(element-wise) 연산을 수행.
* np.ndarray 클래스: NumPy 패키지의 기본 데이터 타입. n-dimensional array(n차원 배열).


In [17]:
num_list1 = [1, 2, 3]
num_list2 = [10, 20, 30]
# 같은 인덱스의 원소들끼리 더하기한 결과
add = [x + y for x, y in zip(num_list1, num_list2)]
add

[11, 22, 33]

In [19]:
num_arr1 = np.array([1, 2, 3])
print(type(num_arr1))
print(num_arr1)

<class 'numpy.ndarray'>
[1 2 3]


In [20]:
num_arr2 = np.array([10, 20, 30])
print(num_arr2)

[10 20 30]


np.ndarray에서 사칙연산은 같은 인덱스의 원소들끼리 수행됨.

In [21]:
num_arr1 + num_arr2

array([11, 22, 33])

In [22]:
num_arr1 * num_arr2

array([10, 40, 90])

In [26]:
num_list1 + num_arr1  # np.array(num_list1) + num_arr1

array([2, 4, 6])

scalar multiplication: `np.ndarray * number`, `number * np.ndarray`

In [28]:
num_arr1 * 3  # element-wise 연산 수행

array([3, 6, 9])

In [30]:
print(num_arr1, num_arr2)
# np.dot(a, b) 함수
np.dot(num_arr1, num_arr2)  # dot product = 1 * 10 + 2 * 20 + 3 * 30

[1 2 3] [10 20 30]


140

In [31]:
# np.ndarray.dot() 메서드
num_arr1.dot(num_arr2)

140

np.ndarray 클래스의 속성들(attributes)

In [37]:
print(num_arr1)
print('ndim =', num_arr1.ndim)  # 차원(dimension)
print('size =', num_arr1.size)  # size: 원소의 개수
print('shape =', num_arr1.shape)  # shape: 각 차원에서의 원소의 개수
print('dtype =', num_arr1.dtype)  # dtype: 배열의 원소들의 데이터 타입

[1 2 3]
ndim = 1
size = 3
shape = (3,)
dtype = int64



* Python 숫자 타입
    * 정수: `int`
    * 실수: `float`
* NumPy 숫자 타입
    * 정수: `int8`, `int16`, `int32`, `int64`, ...
    * 실수: `float16`, `float32`, `float64`, ...


# 2차원 배열

In [38]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [42]:
print('ndim =', arr_2d.ndim)
print('size =', arr_2d.size)
print('shape =', arr_2d.shape)
print('dtype =', arr_2d.dtype)

ndim = 2
size = 6
shape = (2, 3)
dtype = int64


In [43]:
arr_2d_2 = np.array([[1, 1, 1], [2, 2, 2]])
print(arr_2d_2)

[[1 1 1]
 [2 2 2]]


In [44]:
print(arr_2d + arr_2d_2)

[[2 3 4]
 [6 7 8]]


2차원 ndarray의 dot product

> `(n, m) @ (m, k) = (n, k)`


In [45]:
arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])  # (2, 3) shape
arr2 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])  # (3, 2) shape
print(np.dot(arr1, arr2))  #> (2, 2) shape

[[22 28]
 [49 64]]


In [46]:
print(np.dot(arr2, arr1))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


# np.ndarray 객체 생성 함수


`np.array(object)`

* object: 배열과 비슷한 객체. `list`, `tuple`, `ndarray`, ...


In [49]:
# 0 이상 10 이하의 짝수들로 이루어진 ndarray
evens = np.array([2 * x for x in range(6)])
print(evens)

[ 0  2  4  6  8 10]



`np.arange(start, end, step)`

* `range(start, end, step)` 사용 방법과 동일
* 1차원 ndarray를 생성


In [50]:
# 1 이상 10 이하의 홀수들로 이루어진 1차원 ndarray
odds = np.arange(1, 11, 2)
print(odds)

[1 3 5 7 9]



`np.ndarray.reshape(shape)` 메서드

`np.reshape(array, newshape)` 함수


In [52]:
# 메서드
arr = np.arange(12).reshape((3, 4))  # shape은 1차원인 경우 정수, 2차원 이상인 경우 tuple로 전달
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
arr_1d = np.arange(12)
arr_2d = np.reshape(arr_1d, (4, 3))  # 함수
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
