<a href="https://colab.research.google.com/github/JakeOh/202105_itw_bd26/blob/main/lab_da/da02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Array Indexing

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# indexing: 인덱스를 사용해서 배열의 원소 참조
print(arr[0])  # 시작 인덱스는 0
print(arr[9])  # 배열의 마지막 인덱스는 원소개수 - 1
print(arr[-1])

0
9
9


In [9]:
# slicing: [start, end) 범위의 원소들로 이루어진 부분집합(배열)
print(arr[0:5])
print(arr[:5])  # 시작 인덱스 0은 생략 가능
print(arr[5:])  # 끝 인덱스가 생략되면 배열의 끝까지 slicing
print(arr[-3:])

[0 1 2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[7 8 9]


## fancy indexing

* 배열과 비슷한 객체(ndarry, list, tuple, ...)를 사용해서 indexing하는 방법
* fancy indexing의 결과는 ndarray!


In [16]:
np.random.seed(1)
arr = np.random.randint(100, size=10)
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [19]:
print(arr[[1, 3, 5]])

[12  9  5]


In [20]:
print(arr[1])  # indexing: 원소 하나를 참조
print(arr[[1]])  # fancy indexing: 원소 하나를 갖는 ndarray

12
[12]


## boolean indexing

* 논릿값(True, False)들의 배열(리스트, 튜플)을 사용한 fancy indexing
* 조건을 만족하는 원소들로 이루어진 부분집합 ndarray를 생성


In [23]:
bools = np.array([True, False] * 5)
print(bools)
print(arr)
print(arr[bools])

[ True False  True False  True False  True False  True False]
[37 12 72  9 75  5 79 64 16  1]
[37 72 75 79 16]


In [26]:
# arr의 원소들 중 짝수들로만 이루어진 ndarray
print(arr)
print(arr % 2 == 0)  # element-wise 연산
print(arr[arr % 2 == 0])

[37 12 72  9 75  5 79 64 16  1]
[False  True  True False False False False  True  True False]
[12 72 64 16]


In [27]:
# arr 원소들 중 홀수들로만 이루어진 ndarray
arr[arr % 2 == 1]

array([37,  9, 75,  5, 79,  1])

# 통계 함수/메서드

* 함수: `np.function_name(ndarry)`
* 메서드: `np.ndarray.method_name()`


In [30]:
print(arr)
print(np.sum(arr))  # 함수
print(arr.sum())  # 메서드

[37 12 72  9 75  5 79 64 16  1]
370
370
