<a href="https://colab.research.google.com/github/JakeOh/202105_itw_bd26/blob/main/lab_ml/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# 모든 원소가 1.0인 배열 생성
arr = np.ones((3, 4))  # 파라미터 dtype의 기본값은 np.float64(64bits에 저장되는 실수) 타입.
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


`ndarray` 클래스의 속성들(attributes)

In [3]:
arr.dtype  # 배열 원소의 데이터 타입

dtype('float64')

In [4]:
arr.shape  # 배열의 각 축(axis)을 따라서 있는 원소들의 개수들의 tuple

(3, 4)

In [5]:
arr.size  # 배열의 전체 원소 개수

12

In [6]:
arr.ndim  # 배열의 차원의 개수. 배열의 축(axis)의 개수

2

In [7]:
# [1, 6) 범위의 정수들로 이루어진 1차원 배열
arr =  np.arange(1, 6)
print(arr)

[1 2 3 4 5]


In [9]:
print('dtype:', arr.dtype)
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)

dtype: int64
shape: (5,)
size: 5
ndim: 1


In [10]:
# 3차원 배열
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [13]:
print('dtype:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtype: int64
ndim: 3
shape: (2, 3, 4)
size: 24


In [14]:
print(arr[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[0, 0])

[1 2 3 4]


In [16]:
print(arr[0, 0, 0])

1


* Python list의 인덱스 사용방법: `list[a][b][c]...`
* numpy ndarray의 인덱스 사용방법:
    * `array[a][b][c]...`
    * `array[a, b, c, ...]`

slicing

In [17]:
# 1차원 배열
np.random.seed(1)
arr = np.random.rand(10)
print(arr)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [18]:
arr[1:5]  # [1, 5) 범위의 원소들로 이루어진 부분집합(1차원 array)

array([7.20324493e-01, 1.14374817e-04, 3.02332573e-01, 1.46755891e-01])

In [19]:
# 2차원 배열
arr = np.arange(1, 21).reshape((4, 5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
# row는 전체 선택, column은 처음 2개 선택
print(arr[:, 0:2])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


In [21]:
# 첫 2개 row를 선택, 모든 column 선택
print(arr[0:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [29]:
# 3차원 배열
arr = np.arange(1, 61).reshape((3, 4, 5))
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [24]:
print(arr[:2, :, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [25]:
print(arr[:1, :, :])  #> slicing -> 3차원 배열

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [26]:
print(arr[0])  #> 원소 참조 -> 2차원 배열

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
