<a href="https://colab.research.google.com/github/JakeOh/202105_itw_bd26/blob/main/lab_ml/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# `np.ndarray` 속성(attribute)

In [2]:
# 모든 원소가 1.0인 배열 생성
arr = np.ones((3, 4))  # 파라미터 dtype의 기본값은 np.float64(64bits에 저장되는 실수) 타입.
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


`ndarray` 클래스의 속성들(attributes)

In [3]:
arr.dtype  # 배열 원소의 데이터 타입

dtype('float64')

In [4]:
arr.shape  # 배열의 각 축(axis)을 따라서 있는 원소들의 개수들의 tuple

(3, 4)

In [5]:
arr.size  # 배열의 전체 원소 개수

12

In [6]:
arr.ndim  # 배열의 차원의 개수. 배열의 축(axis)의 개수

2

In [7]:
# [1, 6) 범위의 정수들로 이루어진 1차원 배열
arr =  np.arange(1, 6)
print(arr)

[1 2 3 4 5]


In [9]:
print('dtype:', arr.dtype)
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)

dtype: int64
shape: (5,)
size: 5
ndim: 1


In [10]:
# 3차원 배열
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [13]:
print('dtype:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtype: int64
ndim: 3
shape: (2, 3, 4)
size: 24


# `np.ndarray` indexing

In [14]:
print(arr[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[0, 0])

[1 2 3 4]


In [16]:
print(arr[0, 0, 0])

1


* Python list의 인덱스 사용방법: `list[a][b][c]...`
* numpy ndarray의 인덱스 사용방법:
    * `array[a][b][c]...`
    * `array[a, b, c, ...]`

# `np.ndarray` slicing

In [17]:
# 1차원 배열
np.random.seed(1)
arr = np.random.rand(10)
print(arr)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [18]:
arr[1:5]  # [1, 5) 범위의 원소들로 이루어진 부분집합(1차원 array)

array([7.20324493e-01, 1.14374817e-04, 3.02332573e-01, 1.46755891e-01])

In [19]:
# 2차원 배열
arr = np.arange(1, 21).reshape((4, 5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
# row는 전체 선택, column은 처음 2개 선택
print(arr[:, 0:2])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


In [21]:
# 첫 2개 row를 선택, 모든 column 선택
print(arr[0:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [29]:
# 3차원 배열
arr = np.arange(1, 61).reshape((3, 4, 5))
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [24]:
print(arr[:2, :, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [25]:
print(arr[:1, :, :])  #> slicing -> 3차원 배열

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [26]:
print(arr[0])  #> 원소 참조 -> 2차원 배열

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# `np.ndarray` 모양(shape) 변경

* `np.ndarray.reshape(shape)`
* `np.ndarray.ravel()`
* `np.ndarray.flatten()`
* `np.newaxis` 이용


In [30]:
# 1차원 배열 생성
arr_1d = np.arange(1, 13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
# 1차원 배열 arr_1d를 (3, 4) shape을 갖는 2D 배열로 변환
arr_2d = arr_1d.reshape((3, 4))
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
# 1차원 배열 arr_1d를 row가 2개인 2D 배열로 변환
# shape을 argument로 전달할 때, 자동 계산할 수 있는 1개 차원의 수는 -1로 대체가능함.
arr_2d = arr_1d.reshape((2, -1))
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [36]:
# 1차원 배열 arr_1d를 column이 3개인 2D 배열로 변환
arr_2d = arr_1d.reshape((-1, 3))
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
# 2차원 배열 arr_2d를 1차원 배열로 변환
result = arr_2d.reshape(4*3)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
result = arr_2d.reshape((12,))
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
arr_2d.reshape((-1,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr_1d = np.arange(1, 49)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [43]:
# 1차원 배열 arr_1d를 (4, 4, 3) shape을 갖는 3차원 배열로 변환
arr_3d = arr_1d.reshape((4, 4, 3))
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45],
        [46, 47, 48]]])

In [44]:
arr_1d.reshape((4, 4, -1))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45],
        [46, 47, 48]]])

In [45]:
# 3차원 배열 arr_3d를 1차원 배열로 변환
result = arr_3d.reshape(4*4*3)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [46]:
arr_3d.reshape((48,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [47]:
arr_3d.reshape((-1,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [54]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
# 2D 배열을 1D 배열로 변환
raveled = arr_2d.ravel()  # 1차원으로 변환된 view를 리턴.
raveled

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
flattened = arr_2d.flatten()  # 1차원으로 변환된 복사본을 리턴
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
flattened[0] = 100  # flatten() 함수의 결과에서 원소를 변경
print(flattened)
print(arr_2d)  # 원본 2D 배열에는 영향을 미치지 않음!

[100   2   3   4   5   6   7   8   9  10  11  12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [58]:
raveled[0] = 100  # ravel() 함수의 결과에서 원소를 변경
print(raveled)
print(arr_2d)  # 원본 2D 배열에 영향을 미침!

[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]


In [52]:
# 3D 배열을 1D 배열로 변환
arr_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [53]:
arr_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

## `np.newaxis` 속성을 사용한 차원 늘리기

In [66]:
a = np.arange(1, 6)  # (5,) shape을 갖는 1D 배열
print(a)
print('ndim:', a.ndim)
print('shape:', a.shape)

[1 2 3 4 5]
ndim: 1
shape: (5,)


In [67]:
col_vector = a[:, np.newaxis]
print(col_vector)
print('ndim:', col_vector.ndim)
print('shape:', col_vector.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
ndim: 2
shape: (5, 1)


In [68]:
a.reshape((5, 1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [69]:
a.reshape((-1, 1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [71]:
row_vector = a[np.newaxis, :]
print(row_vector)
print('ndim:', row_vector.ndim)
print('shape:', row_vector.shape)

[[1 2 3 4 5]]
ndim: 2
shape: (1, 5)


In [72]:
a.reshape((1, 5))

array([[1, 2, 3, 4, 5]])

In [73]:
a.reshape((1, -1))

array([[1, 2, 3, 4, 5]])

In [74]:
a = np.arange(1, 17).reshape((4, 4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [75]:
a[:, :, np.newaxis]

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16]]])

In [80]:
a.reshape((4, 4, 1))

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16]]])

In [82]:
a[np.newaxis, :, :]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [83]:
a.reshape((1, 4, 4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

# concatenate

* `np.concatenate([a1, a2, ...], axis=0)`: 행 또는 열 방향으로 이어붙이기
* `np.r_[a1, a2]`: 행 이어붙이기(row concatenation)
* `np.c_[a1, a2]`: 열 이어붙이기(column concatenation)

In [84]:
# (2, 3) shape을 갖는 2D 배열
a1 = np.arange(1, 7).reshape((2, 3))
print(a1)

[[1 2 3]
 [4 5 6]]


In [85]:
# (1, 3) shape을 갖는 2D 배열
a2 = np.array([[7, 8, 9]])
print(a2)

[[7 8 9]]


In [86]:
np.concatenate([a1, a2])  # axis=0인 경우는 생략 가능(default)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
np.r_[a1, a2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a3 = np.array([[10],
               [20]])
a3

array([[10],
       [20]])

In [90]:
np.concatenate([a1, a3], axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [91]:
np.c_[a1, a3]

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

# Broadcasting

* `np.ndarray`의 산술연산(+, -, *, /, //, %, ...)은 같은 위치(인덱스)의 원소들끼리(element-wise) 계산됨.
* 서로 shape이 다른 배열들 사이에서 산술연산이 가능하도록 shape을 맞춰서 연산하는 방법 -> broadcast

In [93]:
a = np.array([1, 2, 3])     # (3,) shape을 갖는 1D 배열
b = np.array([1, 2, 3, 4])  # (4,) shape을 갖는 1D 배열
# a + b
#> ValueError: operands could not bes broadcat together with shapes (3,) (4,) 
#> 배열 a와 배열 b는 모양을 같은 shape으로 맞출 수 없다.

## ndarray와 scalar(숫자 한개)의 broadcast 연산

In [97]:
a

array([1, 2, 3])

In [96]:
a + 10

array([11, 12, 13])

In [98]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
a2 + 10

array([[11, 12, 13],
       [14, 15, 16]])

## 2D array와 1D array, 또는 2D array와 2D array에서의 broadcast

In [100]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # (2, 3) shape을 갖는 2D array
b = np.array([10, 20, 30])  # (3, ) shape을 1D array

In [101]:
a + b  # (3,) 1D ---> (1, 3) 2D ---> (2, 3) 2D array

array([[11, 22, 33],
       [14, 25, 36]])

In [102]:
c = np.array([[1, 2, 3]])  # (1, 3) shape을 갖는 2D array
a + c

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
d = np.array([10, 20])  # (2,) shape을 갖는 1D array
# a + d
#> ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [104]:
e = np.array([[10],
              [20]])  # (2, 1) shape을 갖는 2D array

In [105]:
a + e

array([[11, 12, 13],
       [24, 25, 26]])

## broadcast의 활용

* **표준화(standardization)**: 평균이 0이 되고, 표준편차를 1이 되도록 변수들의 스케일을 변환하는 것.
* **정규화(normalization)**: 최솟값이 0이 되고, 최댓값이 1이 되도록 변수들의 스케일을 변환하는 것.

In [106]:
x = np.array([1, 2, 3, 4, 5])

In [107]:
np.mean(x)

3.0

In [108]:
np.std(x)

1.4142135623730951

In [110]:
# 표준화
x_std = (x - np.mean(x)) / np.std(x)
x_std

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [112]:
# 정규화
x_norm = (x - np.min(x)) / (np.max(x) - np.min(x))
x_norm

array([0.  , 0.25, 0.5 , 0.75, 1.  ])