<a href="https://colab.research.google.com/github/JakeOh/202105_itw_bd26/blob/main/lab_ml/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# `np.ndarray` 속성(attribute)

In [2]:
# 모든 원소가 1.0인 배열 생성
arr = np.ones((3, 4))  # 파라미터 dtype의 기본값은 np.float64(64bits에 저장되는 실수) 타입.
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


`ndarray` 클래스의 속성들(attributes)

In [3]:
arr.dtype  # 배열 원소의 데이터 타입

dtype('float64')

In [4]:
arr.shape  # 배열의 각 축(axis)을 따라서 있는 원소들의 개수들의 tuple

(3, 4)

In [5]:
arr.size  # 배열의 전체 원소 개수

12

In [6]:
arr.ndim  # 배열의 차원의 개수. 배열의 축(axis)의 개수

2

In [7]:
# [1, 6) 범위의 정수들로 이루어진 1차원 배열
arr =  np.arange(1, 6)
print(arr)

[1 2 3 4 5]


In [9]:
print('dtype:', arr.dtype)
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)

dtype: int64
shape: (5,)
size: 5
ndim: 1


In [10]:
# 3차원 배열
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [13]:
print('dtype:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtype: int64
ndim: 3
shape: (2, 3, 4)
size: 24


# `np.ndarray` indexing

In [14]:
print(arr[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[0, 0])

[1 2 3 4]


In [16]:
print(arr[0, 0, 0])

1


* Python list의 인덱스 사용방법: `list[a][b][c]...`
* numpy ndarray의 인덱스 사용방법:
    * `array[a][b][c]...`
    * `array[a, b, c, ...]`

# `np.ndarray` slicing

In [17]:
# 1차원 배열
np.random.seed(1)
arr = np.random.rand(10)
print(arr)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [18]:
arr[1:5]  # [1, 5) 범위의 원소들로 이루어진 부분집합(1차원 array)

array([7.20324493e-01, 1.14374817e-04, 3.02332573e-01, 1.46755891e-01])

In [19]:
# 2차원 배열
arr = np.arange(1, 21).reshape((4, 5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
# row는 전체 선택, column은 처음 2개 선택
print(arr[:, 0:2])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


In [21]:
# 첫 2개 row를 선택, 모든 column 선택
print(arr[0:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [29]:
# 3차원 배열
arr = np.arange(1, 61).reshape((3, 4, 5))
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [24]:
print(arr[:2, :, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [25]:
print(arr[:1, :, :])  #> slicing -> 3차원 배열

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [26]:
print(arr[0])  #> 원소 참조 -> 2차원 배열

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# `np.ndarray` 모양(shape) 변경

* `np.ndarray.reshape(shape)`
* `np.ndarray.ravel()`
* `np.ndarray.flatten()`
* `np.newaxis` 이용


In [30]:
# 1차원 배열 생성
arr_1d = np.arange(1, 13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
# 1차원 배열 arr_1d를 (3, 4) shape을 갖는 2D 배열로 변환
arr_2d = arr_1d.reshape((3, 4))
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
# 1차원 배열 arr_1d를 row가 2개인 2D 배열로 변환
# shape을 argument로 전달할 때, 자동 계산할 수 있는 1개 차원의 수는 -1로 대체가능함.
arr_2d = arr_1d.reshape((2, -1))
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [36]:
# 1차원 배열 arr_1d를 column이 3개인 2D 배열로 변환
arr_2d = arr_1d.reshape((-1, 3))
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
# 2차원 배열 arr_2d를 1차원 배열로 변환
result = arr_2d.reshape(4*3)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
result = arr_2d.reshape((12,))
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
arr_2d.reshape((-1,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr_1d = np.arange(1, 49)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [43]:
# 1차원 배열 arr_1d를 (4, 4, 3) shape을 갖는 3차원 배열로 변환
arr_3d = arr_1d.reshape((4, 4, 3))
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45],
        [46, 47, 48]]])

In [44]:
arr_1d.reshape((4, 4, -1))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45],
        [46, 47, 48]]])

In [45]:
# 3차원 배열 arr_3d를 1차원 배열로 변환
result = arr_3d.reshape(4*4*3)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [46]:
arr_3d.reshape((48,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [47]:
arr_3d.reshape((-1,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [54]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
# 2D 배열을 1D 배열로 변환
raveled = arr_2d.ravel()  # 1차원으로 변환된 view를 리턴.
raveled

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
flattened = arr_2d.flatten()  # 1차원으로 변환된 복사본을 리턴
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
flattened[0] = 100  # flatten() 함수의 결과에서 원소를 변경
print(flattened)
print(arr_2d)  # 원본 2D 배열에는 영향을 미치지 않음!

[100   2   3   4   5   6   7   8   9  10  11  12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [58]:
raveled[0] = 100  # ravel() 함수의 결과에서 원소를 변경
print(raveled)
print(arr_2d)  # 원본 2D 배열에 영향을 미침!

[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]


In [52]:
# 3D 배열을 1D 배열로 변환
arr_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [53]:
arr_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

## np.newaxis 속성을 사용한 차원 늘리기